FROM golang:1.26.1-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o /infrastore

FROM alpine:3.22

RUN apk add --no-cache sqlite-libs && adduser -D appuser

WORKDIR /app
RUN mkdir -p /app/db /app/media && chown -R appuser:appuser /app

COPY --from=builder /infrastore /infrastore

USER appuser

EXPOSE 8000

ENTRYPOINT ["/infrastore"]