apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.image.repository }}-cpu-hpa
  namespace: "{{ .Values.appNamespace }}-ns"
spec:
  maxReplicas: {{ default 1 .Values.maxReplicas }}
  minReplicas: {{ default 1 .Values.minReplicas }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.image.repository }}-deployment